const properties = {
  AUDIOTRACKS: "audioTracks",
  AUTOPLAY: "autoPlay",
  BUFFERED: "buffered",
  CONTROLLER: "controller",
  CONTROLS: "controls",
  CONTROLSLIST: "controlsList",
  CROSSORIGIN: "crossOrigin",
  CURRENTSRC: "currentSrc",
  CURRENTTIME: "currentTime",
  DEFAULTMUTED: "defaultMuted",
  DEFAULTPLAYBACKRATE: "defaultPlaybackRate",
  DISABLEREMOTEPLAYBACK: "disableRemotePlayback",
  DURATION: "duration",
  ENDED: "ended",
  ERROR: "error",
  LOOP: "loop",
  MEDIAKEYS: "mediaKeys",
  MUTED: "muted",
  NETWORKSTATE: "networkState",
  PAUSED: "paused",
  PLAYBACKRATE: "playbackRate",
  PRELOAD: "preload",
  PRESERVESPITCH: "preservesPitch",
  READYSTATE: "readyState",
  SEEKABLE: "seekable",
  SEEKING: "seeking",
  SINKID: "sinkId",
  SRC: "src",
  SRCOBJECT: "srcObject",
  TEXTTRACKS: "textTracks",
  VIDEOTRACKS: "videoTracks",
  VOLUME: "volume",
}

export { properties };